name: Terraform Helm Update
on:
  workflow_dispatch:

jobs:
  autorelease:
    name: Update Helm releases in Terraform modules
    runs-on: ubuntu-latest
    steps:
      # Checkout the code so it's mounted to the Docker action
      - name: Checkout Code
        uses: actions/checkout@v3
      
      # Run the docker action
      - name: Helm version update
        uses: clarkjohnd/terraform-helm-digests@v0.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          quay-username: ${{ secrets.QUAY_USERNAME }}
          quay-password: ${{ secrets.QUAY_PASSWORD }}
          gcr-json-key: ${{ secrets.GCR_JSON_KEY }}
          aws-access-key-id: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}
